# Change these first
owner: iphysresearch # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: "IPhysResearch"
    url: https://iphysresearch.github.io/
  - name: "IPhysResearch | Blog"
    url: https://iphysresearch.github.io/blog/
  - name: "IPhysResearch | Profile"
    url: https://iphysresearch.github.io/-he.wang/
  - name: "IPhysResearch | Survey4GWML"
    url: https://iphysresearch.github.io/Survey4GWML/
  - name: "IPhysResearch | PhDthesis_html"
    url: https://iphysresearch.github.io/PhDthesis_html/
#   - name: Wikipedia
#     url: https://en.wikipedia.org
#   - name: Hacker News
#     url: https://news.ycombinator.com
#   - name: Broken Site
#     url: https://thissitedoesnotexist.com
#   - name: Secret Site
#     url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://iphysresearch.github.io/blog/images/icon_hudcd6a43fd2ad103425a861c92af1936d_37564_512x512_fill_lanczos_center_2.png
  name: IPhysResearch Status
  introTitle: "IPhysResearch Website Health Monitor."
  introMessage: This website gives an update on the health and uptime of IPhysResearch and related websites.
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://iphysresearch.github.io/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
